name: My First Automation

on:
  push:
    branches:
      - main
  pull_request:
    paths:
          - 'storybook/**'
  workflow_dispatch:
    inputs:
        story_title:
          description: "A short title for the story"
          required: true
        author_name:
          description: "The author's name"
          required: true
   

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run:  echo "Once upon a time in a faraway land"
        		  echo "<Story Title Input> was written by <Author Name Input>"
        		  echo "This whimsical tale takes you on a journey through a magical forest where every flower could talk."
        		  echo "Will you explore its secrets?
